name: CI

on: [ push, pull_request ]

jobs:

  phpstan:

    name: phpstan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-interaction

      - name: Run Static Analysis
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --error-format=github

  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ "8.3", "8.4", "8.5" ]
    name: PHP ${{ matrix.php-versions }} Test on ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: xdebug

      - name: Install composer dependencies
        run: |
          if [[ "${{ matrix.php-versions }}" == "8.5" ]]; then
            composer install --prefer-dist --no-interaction --ignore-platform-req=php
          else
            composer install --prefer-dist --no-interaction
          fi

      - name: PHPUnit
        run: ./vendor/bin/phpunit --configuration=phpunit.xml --coverage-text
